import atexit
import sys, os, glob

def print_build_failures():
    from SCons.Script import GetBuildFailures
    err_list = list()
    log_file = open("./scons.log", 'w')
    for bf in GetBuildFailures():
        #print "%s failed: %s" % (bf.node, bf.errstr)
        err_list.append("!!!!" + bf.errstr)
        log_file.write(bf.errstr) 
    print err_list
    log_file.close()

print "!!before build." 
env = Environment()
env.Program(target='main', source=[glob.glob('*.cpp')])
env.Append( CXXFLAGS = ['-std=c++11','-Wall']) #-pedantic，令編譯器拒絕非標準特性。
atexit.register(print_build_failures) 
print "!!after trying build."
SConscript('SConscript')
print_build_failures()

# vim: set ft=python:
